# Generated by Django 3.0.5 on 2020-04-11 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_gambar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gambar',
            name='gambar',
            field=models.FileField(upload_to=''),
        ),
    ]
