# Generated by Django 3.0.5 on 2020-04-15 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_auto_20200411_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
